### ISSUE TITLE
Ability to globally exclude file pattern matches

### ISSUE THREAD

**Issue by Sija** [crystal-ameba/ameba#124]
I'd like to suggest 2 things:
- adding a way to exclude files from processing - similarly to #61, but based on path glob pattern in the first place - and not on the rule, like it is atm.
- changing `Exclude` to accept an array of patterns, and not just a single one like it is now

point no. 1 could also apply to inline comments with possibly a syntax like `# ameba:disable *`

**Comment by veelenga** [comment]
> adding a way to exclude files from processing - similarly to #61, but based on path glob pattern in the first place - and not on the rule, like it is atm.

This makes sense, i am going to add this.

> changing Exclude to accept an array of patterns, and not just a single one like it is now

this works. For example, here is a valid config:

```yml
# Problems found: 4
# Run `ameba --only Style/RedundantBegin` for details
Style/RedundantBegin:
  Description: Disallows redundant begin blocks
  Enabled: true
  Severity: Convention
  Excluded:
  - src/sidekiq/server/processor.cr
  - src/sidekiq/web_helpers.cr
  - src/sidekiq/api.cr

```
