### ISSUE TITLE
Error: Index out of bounds

### ISSUE THREAD

**Issue by jwoertink** [crystal-ameba/ameba#168]
I'm not sure why, but I just started getting this error both locally, and in our CI

https://github.com/luckyframework/avram/pull/495/checks?check_run_id=1295328991

```
Finished in 988.8 milliseconds

279 inspected, 0 failures.
Error: Index out of bounds
```

It must be something in that PR specifically. I wonder if it's something with the fact that I have macro args called `if` and `unless` 😬 

```
shards:
  ameba:
    git: https://github.com/crystal-ameba/ameba.git
    version: 0.13.2
```
