### ISSUE TITLE
Invalid memory access on Alpine Linux

### ISSUE THREAD

**Issue by snacks02** [crystal-ameba/ameba#354]
Sometimes Ameba randomly fails in GitHub Actions with:

![image](https://user-images.githubusercontent.com/41530422/217810393-d84ae53d-eceb-449f-a76e-cd8b98b30eba.png)

`ci.yml`:

```yaml
name: GitHub Actions

on: push

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - uses: actions/checkout@v3
      - run: shards install
      - run: bin/ameba
      - run: crystal tool format --check
      - run: crystal spec
```

`shard.yml`:

```yaml
development_dependencies:
  ameba:
    github: crystal-ameba/ameba
    version: ~> 1.4.0
```

Rerunning fixes the issue, but would be great to fix this this in Ameba.

Happy to provide additional information if needed.
