### ISSUE TITLE
excludes files for all rules

### ISSUE THREAD

**Issue by noraj** [crystal-ameba/ameba#365]
For `.ameba.yml`, is there a way to excludes files for all rules (not on a per-rule basis) ?

With rubocop I can do that to exclude some files for all rules:

```yml
AllCops:
  Exclude:
    - 'customdir/*.rb'
```
