### ISSUE TITLE
Add rules for enforcing type restrictions on vars and parameters

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#502]
I'm imagining this would be a few rules, and not sure what namespace they would fall under. Something like:

```yml
Typing/InstanceVarTypeRestriction: # and ClassVarTypeRestriction
  Enabled: true

Typing/LocalVarTypeRestriction:
  Enabled: true
  
Typing/MethodParamTypeRestriction:
  Enabled: true
  DefaultValue: false
  PrivateMethods: false # don't require on private methods
  ProtectedMethods: false
  BlockParam: false # whether typing is required for block params

Typing/MethodReturnTypeRestriction:
  Enabled: true
  PrivateMethods: false
  ProtectedMethods: false

Typing/ProcReturnTypeRestriction:
  Enabled: true

# Maybe some others, can't think of any others currently
```

This would be disabled by default. It wouldn't be perfect, but would definitely be good enough for my use-cases. If this feature would be welcome, I can start prototyping an implementation.

**Comment by nobodywasishere** [comment]
For `getter`/`setter`/`record`, there could be a rule like:

```yml
Typing/MacroCallVarTypeRestriction:
  Enabled: true
  MacroNames:
   - record
   - getter
   - setter
   - property
```
