### ISSUE TITLE
`Style/ParenthesesAroundCondition` correction putting right parenthesis on newline when condition ends with implicit call

### ISSUE THREAD

**Issue by nobodywasishere** [crystal-ameba/ameba#548]
Config:
```yml
Style/ParenthesesAroundCondition:
  Description: Disallows redundant parentheses around control expressions
  ExcludeTernary: false
  AllowSafeAssignment: true
  Enabled: true
  Severity: Convention
```

Example:

```crystal
if var = method.try &.call
  puts var
end
```

Is corrected to:

```crystal
if (var = method.try &.call
)  puts var
 # ^^^^ error: unexpected token: "puts"
end
```

And should be:

```crystal
if (var = method.try &.call)
  puts var
end
```
